version: '3.8'

services:
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    container_name: nginx
    image: nginx:${IMAGE_TAG}
    labels:
      - ${LABLE}
    depends_on:
      - backend
    ports:
      - '443:443'
    secrets:
      - nginx_crt
      - nginx_key
    networks:
      - transcendence
    restart: always

  postgres:
    build:
      context: .
      dockerfile: postgres/Dockerfile
    container_name: postgres
    image: postgres:${IMAGE_TAG}
    labels:
      - ${LABLE}
    env_file:
      - .env
    ports:
     - '5432:5432'
    volumes:
      - db_volume:/var/lib/postgresql/data
    networks:
      - transcendence
    restart: always

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    image: backend:${IMAGE_TAG}
    labels:
      - ${LABLE}
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - '8000:8000'
    networks:
      - transcendence
    restart: always

volumes:
  db_volume:
    driver_opts:
      o: bind
      type: none
      device: ${postgres_dir}

networks:
  transcendence:
    driver: bridge

secrets:
  nginx_crt:
    file: ${ssl_dir}/${crt_name}
  nginx_key:
    file: ${ssl_dir}/${key_name}

